name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: flutter-actions/setup-flutter@6e2468fd827c4a7337cd4b835a6049b78bc0bd1f
        with:
          channel: stable
      - name: Check release version
        shell: bash
        run: |
          version=$(sed -n 's/^version: *//p' pubspec.yaml)
          if [[ "$GITHUB_REF_NAME" != "v$version" ]]; then
            echo "Tag $GITHUB_REF_NAME does not match pubspec.yaml version $version"
            exit 1
          fi
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  publish:
    needs: validate
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
